# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on: 
  push:
    tags:
    - '*'

jobs:
  build:
    strategy:
      matrix:
        GOOS: ['linux', 'windows']
        GOARCH: ['amd64']
        include:
        - GOOS: windows
          X: .exe
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Build
      run: |
        mkdir -p dist
        go build -o dist -v ./...
      env:
        GOOS: ${{ matrix.GOOS }}
        GOARCH: ${{ matrix.GOARCH }}

  upload:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: ncipollo/release-action@v1
      with:
        allowUpdates: true
        artifacts: "dist/*"
